version: '3.8'

services:
  #   bot:
  #   build: .
  #  env_file: .env
  #    depends_on:
  #    -bg_removal_bot
  #    - redis
  #  restart: unless-stopped
  #  volumes:
  #    - ./app:/app/app
  #    - ./static:/app/static
  
  bg_removal_bot:
    build: .
    container_name: bg_removal_bot
    depends_on:
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - postgres_timecapsule_network
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./static:/app/static

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"

networks:
  postgres_timecapsule_network:
    external: true
